version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  run_unit_tests:
    executor: node/default
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies    
      - run:
          name: install dependencies
          command: npm ci
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - ~/.npm
      - run:  # https://stackoverflow.com/a/72633324/9273261
          command: |
            wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            sudo apt-get update -y
            sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            npm run test
          name: Run tests

workflows:
  run_tests:
    jobs:
      - run_unit_tests
