version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  run_test_suite:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:  # https://stackoverflow.com/a/72633324/9273261
          command: |
            wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy_to_heroku:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy_to_heroku-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  run_tests_and_deploy:
    jobs:
      - run_test_suite
      - deploy_to_heroku:
          requires:
            - run_test_suite # only deploy_to_heroku if the run_test_suite job has completed
          filters:
            branches:
              only: main # only deploy_to_heroku when on main
