version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  run_test_suite:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:  # https://stackoverflow.com/a/72633324/9273261
          command: |
            wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
            npm run test
            npm run acceptance
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  run_tests:
    jobs:
      - run_test_suite
